// THIS FILE IS AUTOMATICALLY GENERATED FROM ../../utils/tabler-icons.json. DO NOT EDIT MANUALLY.

import * as React from 'react';
import type { IconProps } from '@tabler/icons-react'; // FIX: Use 'type' for IconProps
import { IconBrandGithub, IconExternalLink, IconBook, IconCircleCheck, IconRocket, IconCloud, IconInfoCircle, IconSearch } from '@tabler/icons-react';


// Central map of ALL imported icons (Matches tabler-icons.json)
export const IconMap: { [key: string]: React.FC<IconProps> } = {
  IconBrandGithub: IconBrandGithub,
  IconExternalLink: IconExternalLink,
  IconBook: IconBook,
  IconCircleCheck: IconCircleCheck,
  IconRocket: IconRocket,
  IconCloud: IconCloud,
  IconInfoCircle: IconInfoCircle,
  IconSearch: IconSearch
};

/**
 * Maps a string icon name (e.g., 'IconBrandGithub') to its React component.
 * @param iconName The string name of the icon from the database.
 * @returns The React component or undefined.
 */
export function getIconComponent(iconName: string): React.FC<IconProps> | undefined {
  return IconMap[iconName];
}